Correcao packages
joaovitorassumpcao-zup/StudyGoals pull request #8
Opened 2023-10-04 21:09 UTC by giorgiasantos

Pessoal, preciso que alguém revise aqui. Por algum motivo a questão dos caminhos dos pacotes ainda tava dando ruim pra mim e tive que modificar novamente. 

Adicionei mais algumas coisas que precisei pra seguir com o service de Meta:
- Configuração do JSON nos atributos que usam LocalDateTime;
- Adicionei um INSTANCE na classe do mapper de Meta pra poder usar a conversão;
- Adequação dos métodos do service de Meta pra usar o DTO.

2023-10-04 21:17 UTC, joaovitorassumpcao-zup requested changes
Só precisa renomear para o sigular algumas classes. Fora isso td ok.
Não sei porque o Intellij não me avisou desses outros pacotes.

2023-10-04 21:40 UTC, giorgiasantos commented
Renomeei as classes. Agora acho que os conflitos somem.

2023-10-05 12:41 UTC, elizabetholiveira approved these changes

2023-10-05 14:00 UTC, joaovitorassumpcao-zup approved these changes
Tudo OK

2023-10-05 15:08 UTC, closed without merging